### ISSUE TITLE
codec2 in asterisk 15 iax2 support

### ISSUE THREAD

**Issue by evgenyh** [traud/asterisk-codec2#3] opened 2018-01-09 14:27 UTC
in current released asterisk 15.1.2  iax2 doesn't understand neither codec2 or silk
it does understand opus, but that's all from newly supported codecs.

any chance that it would be possible to add support to silk* and codec2 in asterisk15 iax2 ?
thanks

**Comment by traud** [comment] 2018-01-09 16:33
duplicate of issue #1 

if you feel different, please, comment and re-open this issue

**Closed as completed by traud** 2018-01-09 16:33 UTC
